language: go
go:
- 1.7

install:
- go get -t ./...
- go get github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/goimports

script:
- FIXED=$(goimports ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "goimports - $FIXED file(s) not formatted correctly, please run goimports to fix this." && exit 1; fi
- golint ./...
- go test ./...
